services:
  fastpages: &fastpages
    working_dir: /data
    environment:
      - INPUT_BOOL_SAVE_MARKDOWN=false
    build:
      context: ./_action_files
      dockerfile: ./Dockerfile
    image: fastpages-dev:latest
    logging:
      driver: json-file
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    volumes:
      - .:/data/
    # Add resource limits for efficiency
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  converter:
    <<: *fastpages
    command: /fastpages/action_entrypoint.sh

  watcher:
    <<: *fastpages
    command: watchmedo shell-command --command /fastpages/action_entrypoint.sh --pattern *.ipynb --recursive --drop
    network_mode: host # for GitHub Codespaces https://github.com/features/codespaces/

  jekyll:
    working_dir: /data
    image: fastai/fastpages-jekyll:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - .:/data/
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_GEMFILE=/data/Gemfile
    # Add resource limits for efficiency
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    command: >
      bash -c "gem install bundler -v 2.4.22 && 
               bundle install --retry=3 --jobs=4 && 
               bundle exec jekyll serve --host=0.0.0.0 --port=4000 --trace --strict_front_matter --incremental --livereload"
